### PR TITLE
Use a builder with app selector and misc fixes

### PR DESCRIPTION
**Pull request by hellcp**
This requires testing, but it should fix the situation mentioned in #125

### CODE REVIEW

**Comment by matejdro** [comment]
I've tested it out and I think I still feel dropped frames quite heavily. And this is on OnePlus 7 Pro, which is not really a slouch.

**Comment by matejdro** [comment]
@DreadBoy Is flutter scrolling significantly slower in debug mode?

Code looks fine to me, but it still lags on the device. Can you also take a look at it?

**Comment by DreadBoy** [comment]
Everything is slower in debug mode. If I try to run Pebble on my phone in debug mode, even animations and navigation transitions are lagging... but to be fair, my phone is slow, even emulator works better than my phone.

**Comment by DreadBoy** [comment]
I tested profile and debug modes on my Nokia 7.1, I navigated to alerting apps screen and flicked the list view once so that it scrolled to bottom.
Profile mode:
image
Debug mode:
image
I cropped both images correctly, app in debug mode just can't render that many frames before list view is finished scrolling. Visually it lags in both modes but a bit less in profile mode.

**Comment by DreadBoy** [comment]
Another approach to optimisation would be to make tabbed navigation smarter. Right now all tabs are loaded as soon as user comes from setup flow but it would probably help if only currently active one (or rather 2 active ones in case of animation) would be loaded. I don't know how this would work with navigator yet but I'm sure we can figure out something.

**Comment by hellcp** [comment]
> Another approach to optimisation would be to make tabbed navigation smarter. Right now all tabs are loaded as soon as user comes from setup flow but it would probably help if only currently active one (or rather 2 active ones in case of animation) would be loaded. I don't know how this would work with navigator yet but I'm sure we can figure out something.

We could also only load the tabs that take a long time to load up otherwise on boot, to not make the app feel sluggish when navigating around. I'm not sure we have such a tab yet though. I'm using the debug app on a very low end phone and I get to experience how slow this is though (it really is a good testing phone for this because of that)

**Pull request merged**
