### PR TITLE
Upgrade dependencies for flutter 2

### LINKED ISSUE #120: Migrate to Flutter 2
Opening this for discussion.

### PR DESCRIPTION
**Pull request by AliceGrey**
Not null-safe yet but we're getting there

Fixes #120

### CODE REVIEW

**Comment by DreadBoy** [comment]
You can check if dependencies are on latest version with https://pub.dev/packages/pubspec_update. I'm not saying they are not, just sharing knowledge :)

**Comment by AliceGrey** [comment]
Yep that's what I used for this :) We've got ~5 direct dependencies that are not null-safe yet. I upgraded all of ours to the latest major version.

**Comment by matejdro** [comment]
Do we need all deps to be null-safe or can we mix and match?

**Comment by AliceGrey** [comment]
> Do we need all deps to be null-safe or can we mix and match?

We can mix and match. Null safety won't be enabled until all dependencies are null safe though. Pretty much all plugins are moving to null safe now that Dart 2.12 is out.

**Pull request merged**
