### PR TITLE
Fix calendar sync not working

### PR DESCRIPTION
**Pull request by matejdro**
this fixes the issue where calendar sync stopped working since localization update

### CODE REVIEW

**Comment by matejdro** [comment]
@DreadBoy Is this proper way to get the current locale? I have no idea what I'm doing here.

**Comment by DreadBoy** [comment]
> @DreadBoy Is this proper way to get the current locale? I have no idea what I'm doing here.

It depends on how robust you want to get. Your solution will work until someone add `localeListResolutionCallback` or `localeResolutionCallback` because at that point Flutter won't use native locale resolution but provided callbacks. I can imagine custom callback will implement different algorithm than native platform.

Also, I think Flutter is using some basic algorithm (https://api.flutter.dev/flutter/material/MaterialApp/supportedLocales.html) to resolve locales and that might be different than native resolution, right? So even without custom `localeListResolutionCallback` we might get different results with `supportedLocales` than with Android's resolution (https://developer.android.com/guide/topics/resources/multilingual-support).

The safest way to get correct locale would be to get it from context. I didn't think of implementing that but it should be pretty simple. You should add `Locale` field to `Localization` class (https://github.com/pebble-dev/mobile-app/blob/master/lib/localization/localization.dart#L8) and initialize it in `load`method (https://github.com/pebble-dev/mobile-app/blob/master/lib/localization/localization.dart#L35). Locale in load method is final resolved locale, after native resolution, `localeListResolutionCallback` or anything else. You would then get that locale as `Localization.of(context).locale`.

If you don't have access to context, your way is probably the simplest although prone to bugs.

**Comment by matejdro** [comment]
@DreadBoy I do not have access to the context. What can I do to make it less bug-prone?

**Comment by DreadBoy** [comment]
Hmm, I don't know. Maybe we can implement `localeListResolutionCallback` and use that implementation in `BackgroundReceiver` too? We are then breaking away from Flutter's resolution and if it's updated in the future, we won't get that update. 

Is it too big of a refactor to wire these callbacks with context? [This container](https://github.com/pebble-dev/mobile-app/blob/a4ee891b3be817440d95d184f528488a82fb90e8/lib/background/main_background.dart#L23) probably isn't the same container as provided by [`ProviderScope`](https://github.com/pebble-dev/mobile-app/blob/a4ee891b3be817440d95d184f528488a82fb90e8/lib/main.dart#L24), right? This also feels wrong because there should be only one provider container, created by `ProviderScope` widget and providers should then be fetched from context. 🤷‍♂️

**Comment by matejdro** [comment]
@DreadBoy What do you think about this solution?

**Comment by DreadBoy** [comment]
More robust and probably the best we can achieve without context 👍

**Review by DreadBoy — APPROVED** [review]

**Pull request merged**
