### PR TITLE
Set up the calendar page

### PR DESCRIPTION
**Pull request by hellcp**
Also from the mockups, fully functional, just taken away from the test tab

### CODE REVIEW

**Comment by matejdro** [comment]
This does not build for me:

```
lib/ui/screens/settings.dart:64:34: Error: Getter not found: 'calendar'.
            leading: RebbleIcons.calendar,
                                 ^^^^^^^^
lib/ui/screens/calendar.dart:42:34: Error: Getter not found: 'calendar'.
            leading: RebbleIcons.calendar,
                                 ^^^^^^^^


FAILURE: Build failed with an exception.
```

Did you forget to commit something?

**Comment by hellcp** [comment]
Look at https://github.com/pebble-dev/mobile-app/pull/162

**Comment by matejdro** [comment]
Okay, please mention next time that this depends on the another PR ;)

**Comment by hellcp** [comment]
I should update all the prs to mention that

**Comment by matejdro** [comment]
@hellcp Now that icons are merged, can sync this with master?

**Pull request merged**
