### PR TITLE
Update pubspec

### PR DESCRIPTION
**Pull request by hellcp**
Most of the changes are from riverpod, from the following change: https://github.com/rrousselGit/river_pod/issues/341
There were also slight changes in Uuid, but they are more obvious

The dependencies blocked by other dependencies were marked

### CODE REVIEW

**Comment by hellcp** [comment]
I also rebased device_calendar on the latest devel, but I will leave that for another time (and branch), since it's a lot of fixing null safety after their rewrite among other things https://github.com/hellcp/device_calendar/tree/rebble

**Review by DreadBoy — CHANGES_REQUESTED** [review]
Static analysis finds problems in app in test, check out "Dart Analysis" tab in IntelliJ or log from [CI](https://github.com/pebble-dev/mobile-app/pull/169/checks?check_run_id=2741608692)

**Comment by hellcp** [comment]
I'm switching this to draft since I noticed breaking change of not being able to connect to the watch anymore (which is pretty useful)

**Comment by NoahAndrews** [comment]
When I first installed an app from this branch, I was able to pair to a watch, but sending pings and test notifications did not work.

I then added a tiny bit of logging to the Android layer, installed the new APK (no hot reload), and sending pings and test notifications started working.

I'm not too sure what to make of that.

**Comment by hellcp** [comment]
I should come back to this branch at some point to test it again

**Pull request closed without merging**
