### PR TITLE
Make iOS target compile

### PR DESCRIPTION
**Pull request by q231950**
Thanks for merging the `ios` branch back to `master` - that's great!

Unfortunately the latest state is not compiling. I have had a look and think I got the issues fixed + corrected a warning. These are the changes.

### CODE REVIEW

**Comment by crc-32** [comment]
pigeon.h/.m are in `master` just as Pigeons.h/.m and i dont recall them being any different, are you sure this isnt due to a typo when re-generating the pigeons as I can't see Pigeons.h or pigeon.h being modified in the previous pull request and I just used the github UI so there shouldnt be anything missing. (you can see the intended pigeons command [here](https://github.com/pebble-dev/mobile-app#building-pigeons))

Also thanks again for your contribution, feel free to join the discord at https://rebble.io/discord if you wish as we have a channel dedicated to the app, but there's no obligation of course!

**Comment by q231950** [comment]
@crc-32 could you please check if this compiles fine for you?

Happy wwdc watching later 😉

**Review by crc-32 — APPROVED** [review]
It compiles fine for me, is this now mergable?

**Comment by q231950** [comment]
Yes please, go ahead 🙂

**Pull request merged**
