### PR TITLE
Fixes for a bunch of reported issues

### PR DESCRIPTION
**Pull request by matejdro**
See list of commits for full list

### CODE REVIEW

**Comment by AliceGrey** [comment]
@matejdro doing some testing of the PR. It looks like the app still doesn't disconnect or unpair the watch when forget watch is selected.

**Comment by AliceGrey** [comment]
@matejdro 

I can confirm this fixes: #116, #134, #135

It fixes #108 but it has a weird icon animation when the app opens, the "rock on" hand logo sort of floats up while the window opens. I haven't seen this happen with other apps.

 I wasn't able to reproduce #124 or #118, 
 
 #103 needs more work I think, it still doesn't function as expected.

**Review by AliceGrey — COMMENTED** [review]
I can confirm this fixes: #116, #134, #135

It fixes #108 but it has a weird icon animation when the app opens, the "rock on" hand logo sort of floats up while the window opens. I haven't seen this happen with other apps.

 I wasn't able to reproduce #124 or #118, 
 
 #103 needs more work I think, it still doesn't function as expected. It looks like the app still doesn't disconnect or unpair the watch when forget watch is selected.

**Comment by matejdro** [comment]
Thanks for the review. I've added disconnect for the #103.

I can't reproduce the #108 issue you have (or maybe I don't know what I'm looking for). Can you record your screen?

**Review by AliceGrey — APPROVED** [review]

**Pull request merged**
